metadata:
  description: 
    Sample community config
user:
  RUN_ENVIR: community
  MACHINE: macos
  ACCOUNT: an_account
workflow:
  USE_CRON_TO_RELAUNCH: false
  EXPT_SUBDIR: test_macos
  CCPP_PHYS_SUITE: FV3_GFS_v16
  PREDEF_GRID_NAME: RRFS_CONUS_25km
  DATE_FIRST_CYCL: '2019061518'
  DATE_LAST_CYCL: '2019061518'
  FCST_LEN_HRS: 12
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_ICS: "/Users/username/UFS_SRW_data/input_model_data/FV3GFS/grib2/2019061518"
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: grib2
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: "/Users/username/UFS_SRW_data/input_model_data/FV3GFS/grib2/2019061518"
task_run_fcst:
  QUILTING: true
  LAYOUT_X: 3
  LAYOUT_Y: 2
  WRTCMP_write_tasks_per_group: 2
task_plot_allvars:
  COMOUT_REF: ""
global:
  DO_ENSEMBLE: false  
  NUM_ENS_MEMBERS: 2
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml", "parm/wflow/plot.yaml"]|include }}'
    metatask_run_ensemble:
      task_run_fcst_mem#mem#:
        walltime: 02:00:00
  task_plot_allvars:
    PLOT_FCST_START: 0
    PLOT_FCST_INC: 6
    PLOT_FCST_END: 6
