metadata:
  description: 
    Sample community config
user:
  RUN_ENVIR: community
  MACHINE: macos
  ACCOUNT: an_account
workflow:
  USE_CRON_TO_RELAUNCH: false
  GRID_GEN_METHOD: ESGgrid
  EXPT_SUBDIR: Palisades_f84h
  CCPP_PHYS_SUITE: FV3_WoFS_v0
  DATE_FIRST_CYCL: '2025010618'
  DATE_LAST_CYCL: '2025010918'
  FCST_LEN_HRS: 84
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: gnu
task_make_grid:
  ESGgrid_LON_CTR: -118.50
  ESGgrid_LAT_CTR: 34.50
  ESGgrid_DELX: 1000.0
  ESGgrid_DELY: 1000.0
  ESGgrid_NX: 275
  ESGgrid_NY: 333
  ESGgrid_WIDE_HALO_WIDTH: 6
  ESGgrid_PAZI: 0.0
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: HRRR
  FV3GFS_FILE_FMT_ICS: grib2
  USE_USER_STAGED_EXTRN_FILES: false
  EXTRN_MDL_SOURCE_BASEDIR_ICS: "/Users/bkirtman/UFS_SRW_data/input_model_data/HRRR/grib2/2025010618"
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: HRRR
  LBC_SPEC_INTVL_HRS: 1
  FV3GFS_FILE_FMT_LBCS: grib2
  USE_USER_STAGED_EXTRN_FILES: false
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: "/Users/bkirtman/UFS_SRW_data/input_model_data/HRRR/grib2/2025010618"
  EXTRN_MDL_LBCS_MAX_FCST_HRS: 48
  EXTRN_MDL_LBCS_BRIDGE_INTVL_HRS: 24
task_run_fcst:
  DT_ATMOS: 15
  QUILTING: true
  LAYOUT_X: 3
  LAYOUT_Y: 5
  BLOCKSIZE: 35
  QUILTING: true
  WRTCMP_write_groups: 1
  WRTCMP_write_tasks_per_group: 1
  WRTCMP_output_grid: lambert_conformal
  WRTCMP_cen_lon: '{{ task_make_grid.ESGgrid_LON_CTR }}'
  WRTCMP_cen_lat: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
  WRTCMP_lon_lwr_left: -119.25
  WRTCMP_lat_lwr_left: 33.50
  WRTCMP_stdlat1: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
  WRTCMP_stdlat2: '{{ task_make_grid.ESGgrid_LAT_CTR }}'
  WRTCMP_nx: 150
  WRTCMP_ny: 150
  WRTCMP_dx: '{{ task_make_grid.ESGgrid_DELX }}'
  WRTCMP_dy: '{{ task_make_grid.ESGgrid_DELY }}'
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: Palisades2
task_plot_allvars:
  COMOUT_REF: ""
global:
  DO_ENSEMBLE: false  
  NUM_ENS_MEMBERS: 2
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/coldstart.yaml" ]|include }}'
    metatask_run_ensemble:
      task_run_fcst_mem#mem#:
        walltime: 72:00:00
